### ISSUE TITLE
logo text doesn't show up

### ISSUE THREAD

**Issue by walkccc** [zalando-incubator/hexo-theme-doc#108]
## Expected Behavior
Show up {myText}(which is specified in "/{myFolder}/source/_data/navigation.yaml") right to the logo. 

## Actual Behavior
Right of the logo is a white blank.

## Steps to Reproduce the Problem

  1. In the file: "/{myFolder}/source/_data/navigation.yaml", the first 4 lines:

```javascript
logo:
- text: myText
  type: link
  path: index.html
main:
```

  2. hexo clean
  3. hexo s (or hexo deploy -g)
  4. The webpage didn't show {myText} right to the logo, and it is a blank.

How can I do? Thanks! 

## Specifications

 - NodeJS Version: 8.9.4
 - NPM Version: 5.6.0
 - OS: macOS High Sierra version 10.13.3
 - Hexo Version: 3.5.0

**Comment by rbarilani** [comment]
@walkccc 

Can you try with the snippet below?

```yaml
logo:
  text: myText
  type: link
  path: index.html
```

**Comment by walkccc** [comment]
@rbarilani 

It works! Thanks a lot😁
