### ISSUE TITLE
The code block doesn't show properly on the smartphone.

### ISSUE THREAD

**Issue by walkccc** [zalando-incubator/hexo-theme-doc#109]
## Expected Behavior
The code block is properly(i.e., rectangular) displayed in the browser on a smartphone.

## Actual Behavior
The corner of the code block is not displayed correctly in the browser on a smartphone. There are rectangular hollows in the corner.
![codeblock](https://user-images.githubusercontent.com/14782909/35763914-714f12c6-08f1-11e8-99bc-99b22da3df58.PNG)

## Specifications

 - NodeJS Version: 8.9.4
 - NPM Version: 5.6.0
 - OS: iOS 11.2.1
 - Hexo Version: 3.5.0

**Comment by bhaskarmelkani** [comment]
Hi @walkccc 

I tested it on some devices and it looked good.

Can you please check again, if it works or is broken.

Also it will be helpful if you can provide the details of the device that you are testing on.

Result in iPhone 7(iOs 11.3)
![img_5903](https://user-images.githubusercontent.com/8968871/39129588-2aa5be80-470b-11e8-8192-588dd2fda07b.PNG)

**Comment by rbarilani** [comment]
closed since the requested was unresponsive
