### ISSUE TITLE
How to show specific line numbers of the code block manually?

### ISSUE THREAD

**Issue by walkccc** [zalando-incubator/hexo-theme-doc#111]
## Expected Behavior
I want to specify the line numbers by myself. I'm currently work on a solution of a book. Since I want to correspond to the book's style, I hope I can start the line number "1" from the second line, not the first line. 

In the hexo-theme-doc, It'll show something like this(regardless the syntax.)

```cpp
  1  func(a, b)     
  2      A()        
  3      return B      
```

I hope something like this:
```cpp
     func(a, b)     
  1      A()        
  2      return B   
```

Or sometimes I want it show a specific line number like:

```cpp
  8  func()
```

Is it possible to change this? Thanks a lot!!

## Specifications

 - NodeJS Version: 8.9.4
 - NPM Version: 5.6.0
 - OS: macOS High Sierra version 10.13.3
 - Hexo Version: 3.5.0

**Comment by rbarilani** [comment]
@walkccc Nope it's not possible. You might be able to achieve it with CSS though. 
IMHO it's a really specific use-case and well personally it sounds weird to....

> I hope I can start the line number "1" from the second line, not the first line.

**Comment by walkccc** [comment]
Alternatively, is it possible to start from “0” or turn off the line_numbers functionality so that I can add the number I need by myself. Btw, I think include the copy-and-past feature will be useful.

**Comment by rbarilani** [comment]
@walkccc As you discovered the code highlighter (markdown parser) is not really part of this theme.
In the getting started project we use ```hexo-renderer-marked``` so I will suggest to open an issue there if you are using that renderer too.

**Comment by rbarilani** [comment]
@walkccc, me and @bhaskarmelkani agreed on closing this issue because the feature must be introduced in another component (`hexo-renderer-marked`). Feel free to re-open it maybe specifying a viable alternative.
