### ISSUE TITLE
More convienent way of making Hexo use the theme from node_modules?

### ISSUE THREAD

**Issue by Pizzacus** [zalando-incubator/hexo-theme-doc#112]
So, I was wondering, why do we have to make a symlink to install the theme? It's in order to get Hexo to use the theme from node_modules, right? So that the theme can be updated with npm, yarn or whatever

Well, wouldn't the same thing be achieved by setting the theme option to that folder directly?

Like this:
```yaml
theme: ../node_modules/hexo-theme-doc
```

Because I did test it and it seems to be working, so I was wondering if you did consider this, maybe there are some "side effects" but as far as I can tell, it seems to be working, so I thought I would ask about it

**Comment by rbarilani** [comment]
@Pizzacus Your suggestion was merged to the **master** branch, a release containing that change will be released soon, see [1.0.0-rc milestone](https://github.com/zalando-incubator/hexo-theme-doc/milestone/2)
