### ISSUE TITLE
How to control search behavior?

### ISSUE THREAD

**Issue by kapv89** [zalando-incubator/hexo-theme-doc#114]
## Expected Behavior
I am using this theme to create a documentation website for my ORM, [tabel](https://github.com/fractaltech/tabel).

I am not sure what to do with the search input from the left-menu(shown in the image below)
![screenshot from 2018-02-01 20-35-07](https://user-images.githubusercontent.com/1023032/35685419-b1c91c4c-078f-11e8-9099-6c121337371b.png)

I would be happy if I could somehow remove it, or start making it show search results which are relevant to my ORM's documentation. I am not sure how to do that.

## Actual Behavior
I can neither find the steps I need to take to remove the search bar, nor am I able to figure out how to make the search-input fetch results from the content that I am writing. Right now, its showing results from god knows where. (Screenshot attached)
![screenshot from 2018-02-01 20-40-44](https://user-images.githubusercontent.com/1023032/35685640-45957114-0790-11e8-8aef-e405b16283ee.png)

## Steps to Reproduce the Problem

  1. `git clone https://github.com/zalando-incubator/hexo-theme-doc-seed.git docs`
  2. `cd docs`
  3. `npm install`
  4. `hexo s`
  5. Go to `http://localhost:4000`, and try to search something in the search-bar placed in left menu.

## Specifications

  - NodeJS Version: 8.9.4
  - NPM Version: 5.6.0
  - OS: Ubunntu 17.10
  - Hexo Version: 3.5.0

**Comment by rbarilani** [comment]
Hi @kapv89, I see that you are using the starter project that doesn't contain so much content, when you will start adding your content, search should start also to work better.

BTW you can exclude "pages" from the "search index" using Front-matter in your markdown file, eg:

```md
search: exclude
---

# My Page
...
```

Apparently we forgot to document that option...

At the moment there isn't a way to completely "turn off" the search functionality.

**Comment by kapv89** [comment]
Hi, so I am letting search be for the moment. Closing this issue.
