### ISSUE TITLE
The columns in the table are too close to one another

### ISSUE THREAD

**Issue by walkccc** [zalando-incubator/hexo-theme-doc#115]
## Expected Behavior
I hope that the columns in the markdown table won't be so close to one another(There should be some space between each column.)
<img width="780" alt="goodtable" src="https://user-images.githubusercontent.com/14782909/35763651-b831b05a-08eb-11e8-979c-cf66512d9ebf.png">

## Actual Behavior
The columns in the table are too close to one another.

<img width="224" alt="table" src="https://user-images.githubusercontent.com/14782909/35763587-7b8ef5d2-08ea-11e8-9e77-b88446e9fe29.png">

## Steps to Reproduce the Problem

The codes:

```
| $A$ | $B$ | $O$ | $o$ | $\Omega$ | $\omega$ | $\Theta$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $\lg^k n$ | $n^\epsilon$ | yes | yes | no | no | no |
| $n^k$ | $c^n$ | yes | yes | no | no | no |
| $\sqrt{n}$ | $n^{\sin n}$ | no | no | no | no | no |
| $2^n$ | $2^{n/2}$ | no | no | yes | yes | no |
| $n^{\lg c}$ | $c^{\lg n}$ | yes | no | yes | no | yes |
| $\lg(n!)$ | $\lg(n^n)$ | yes | no | yes | no | yes |
```

## Specifications

  - NodeJS Version: 8.9.4
  - NPM Version: 5.6.0
  - OS: macOS High Sierra version 10.13.3
  - Hexo Version: 3.5.0

Is it possible to adjust this? Thanks a lot.

**Comment by bhaskarmelkani** [comment]
Hi @walkccc 

I tried replicating the issue but couldn't.
Can you check if you are using any library(js, css) for formatting as table borders are also not appearing in ur example.
So maybe something is overwriting the default table styling, can please you check ?

Also, what library are you using for displaying math symbols ?

I tried with [MathJax](https://github.com/mathjax/mathjax) and got the following result.
<img width="443" alt="screen shot 2018-03-14 at 16 58 59" src="https://user-images.githubusercontent.com/8968871/37414318-1f8a9c68-27a9-11e8-851c-ad6e289cefb7.png">

**Comment by dog2cat** [comment]
same problem :cry:

**Comment by rbarilani** [comment]
Closed since the issue due the usage of another plugin
