### ISSUE TITLE
Site title not visible in nav-header

### ISSUE THREAD

**Issue by kapv89** [zalando-incubator/hexo-theme-doc#119]
## Expected Behavior
![screenshot from 2018-02-07 18-58-05](https://user-images.githubusercontent.com/1023032/35918728-dd789892-0c38-11e8-9b52-4d776fbf4070.png)
Navigation menu with site title in its header

## Actual Behavior
![screenshot from 2018-02-07 18-58-52](https://user-images.githubusercontent.com/1023032/35918774-f8159f4c-0c38-11e8-8258-8686be38bad2.png)
Navigation menu doesn't have a site title. You can see the live version here: http://tabel.fractaltech.in/

## Steps to Reproduce the Problem
Not sure. Maybe there is a config property that I have not set properly which you can point me to.

## Specifications

  - NodeJS Version:8.9.4
  - NPM Version: 5.6.0
  - OS: Ubuntu 17.10
  - Hexo Version: 1.0.4

**Comment by walkccc** [comment]
I have the same issue. This doesn’t happen before LOL

**Comment by rbarilani** [comment]
@kapv89 weird... I will have a look... Can you tell me which version of the theme are you using?

@walkccc you said that this was not happening before, did you update the theme, recently?

P.S. Sorry for the late response but both maintainers were on holidays 🌞 🌊 😄  (@rbarilani and @bhaskarmelkani)

**Comment by rbarilani** [comment]
To configure the logo text please see: https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/navigation.html

There is a typo in the ```navigation.yaml``` example, the logo value should defined like so:

*source/_data/navigation.yaml*

```yaml
logo:
  text: My Documentation
  type: link
  path: index.html
``` 

Feel free to re-open if doesn't fix the issue.
