### ISSUE TITLE
Project Partials docs are incorrect.

### ISSUE THREAD

**Issue by scott-orleman** [zalando-incubator/hexo-theme-doc#135]
## Expected Behavior
documentation reflect functionality

## Actual Behavior
'project_partials' is not being used. Object parameter name being used is 'partials'

https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/project-partials.html

documentation should read:

theme_config:
  partials:
    head_start:
      - ./meta.ejs
      - ./stylesheets.ejs
    footer_end: ./scripts.ejs

NOT:
theme_config:
  project_partials:
    head_start:
      - ./meta.ejs
      - ./stylesheets.ejs
    footer_end: ./scripts.ejs

**Comment by rbarilani** [comment]
Fixed by #142
