### ISSUE TITLE
installing hexo-theme-doc results in blank page with no layout: index.html error

### ISSUE THREAD

**Issue by jtcmedia** [zalando-incubator/hexo-theme-doc#139]
## Expected Behavior
http://localhost:4000/ brings up basic template of hexo-theme-doc

## Actual Behavior
blank page with error message `WARN  No layout: index.html`
default landscape theme works fine

## Steps to Reproduce the Problem

  1. hexo init test
  2. npm install hexo-theme-doc --save
  3. modify _config.yml, change theme `theme: ../node_modules/hexo-theme-doc`
  4. `hexo s`

## Specifications

  - NodeJS Version:  8.11.4
  - NPM Version:  5.6.0
  - OS:  Windows 10
  - Hexo Version: 3.7.1

**Comment by kishoretulsiani** [comment]
any update on this or is this project sunset?

**Comment by rbarilani** [comment]
@kishoretulsiani No the project is not on its sunset, it's just that in H1 (this first half year) me and @bhaskarmelkani were really busy on some other business critical projects and more over that, we  always find difficult and really time consuming test and fix bugs on Windows (we don't use Windows and our main company's users are working on Linux and/or OSX). BTW we will really like also to:

a. Have more contributions from externals, in this regard we would really like to know what is blocking you folks to contribute to the project and propose PR(s)?
b. Spend more time in H2 and the long winter in Berlin to fix the current main issues!!

Best regards.

Ruben

**Comment by mdiep** [comment]
• `hexo`: 3.6.0
• `node`: 10.4.1
• `npm`: 6.1.10

I do see in [the hexo docs](https://hexo.io/docs/templates) that:

> At the very least, a theme should contain an index template

which this theme doesn't seem to have? But you clearly have it working on your code, so I'm not sure what the difference is.

**Comment by rbarilani** [comment]
@mdiep Thanks I will have a look tonight with a fresh installation

**Comment by rbarilani** [comment]
@mdiep @jtcmedia Ok I think I have found the problem, if you use `hexo init` instead of the recommended [Getting Started Guide for this Them](https://zalando-incubator.github.io/hexo-theme-doc/get-started.html) you **MUST** uninstall `hexo-generator-index` that is shipped by using the `hexo init` command:

```bash
npm remove hexo-generator-index
hexo cache clean
hexo s
```

**Comment by mdiep** [comment]
Awesome, that did the trick! Thanks!

**Comment by mdiep** [comment]
Thanks again, @rbarilani! This is a beautiful theme. I'm not very familiar with Hexo or Node, so I really appreciate your help with this issue.

**Comment by jtcmedia** [comment]
@rbarilani The [Long Start](https://zalando-incubator.github.io/hexo-theme-doc/get-started.html#Long-Start) instructions, which I was following for an existing project that I wanted to add this theme to, doesn't mention uninstalling `hexo-generator-index`. It might be prudent to add this to these instructions.

**Comment by MasterGroosha** [comment]
I'm still having "No layout" error and index.html is not generated

**Comment by stevage** [comment]
I'm running into this too. Removing hexo-generator-index didn't help me.

**Comment by hsl727261250** [comment]
> I'm still having "No layout" error and index.html is not generated
> NPM 6.9.0, NodeJS 10.16.0 LTS, OS Windows 10
> 
> I did everything from the Long Start, including removing hexo-generator-index plugin. No index.html

after that, ***create a new file named "index.md" in source folder***, and world peace.
