### ISSUE TITLE
How do I disable/hide searchbar on navigation bar?

### ISSUE THREAD

**Issue by rohit-gh** [zalando-incubator/hexo-theme-doc#140]
There are only 5 pages in my documentation and I want to hide/disable search UI button and search bar on the navigation bar. 
I've read the documentation and I could not find a way to do that, can someone help me with this?

**Comment by rbarilani** [comment]
@copsbehindme Hi as stated in the documentation, there isn't a way to turn off the search functionality, a quick hack to just hide the controls will be to use CSS, adding a stylesheet using project partial functionality: https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/project-partials.html
