### ISSUE TITLE
I can't run this theme with hexo and I tried issuse 139

### ISSUE THREAD

**Issue by CMemorY180819** [zalando-incubator/hexo-theme-doc#147]
## Actual Behavior
I just tried with this [GettingStart](https://zalando-incubator.github.io/hexo-theme-doc/get-started.html) Long start. Both of recommended(npm) and not recommended(git)

## Steps to Reproduce the Problem

~~~
  1.  hexo init test
  2. git clone git@github.com:zalando-incubator/hexo-theme-doc.git themes/doc
  3. cd themes/doc && npm install --prod
  4. npm install hexo-renderer-ejs hexo-renderer-marked --save
  5. update _config.yml themes->doc 
~~~

After this, when I'm trying to open localhost:4000. The page keeps loading, so I open the F12 mode. I find out that there are some lack of js(jquery and css)

And then I tried 'npm' 
~~~
1. npm install hexo-theme-doc --save
2. update _config.yml
~~~
And then I find the same question just the same as issuse 139. So I tried to uninstall hexo-generator-index and `hexo clean` and `hexo s` again. The page is just like this `Cannot GET /` .

Plz help me. I really like this theme.

## Specifications

  - NodeJS Version: 10.14.1
  - NPM Version: 6.5.0
  - OS: MacOS
  - Hexo Version: 3.8.0

**Comment by CMemorY180819** [comment]
sry not jquery

~~~
Refused to apply style from 'http://localhost:4000/css/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:125 GET http://localhost:4000/js/script.js net::ERR_ABORTED 404 (Not Found)
~~~

**Comment by CMemorY180819** [comment]
Hello
 When I tried `npm`
The wrong message is blow here.
And then the page `localhost:4000` shows `Cannot GET /`
~~~
INFO  Start processing
INFO  Files loaded in 334 ms
WARN  No layout: archives/index.html
WARN  No layout: archives/2019/index.html
WARN  No layout: archives/2019/01/index.html
INFO  Generated: lunr.json
INFO  Generated: archives/index.html
INFO  Generated: fonts/DressCodeIcons.eot
INFO  Generated: archives/2019/01/index.html
INFO  Generated: fonts/DressCodeIcons.ttf
INFO  Generated: archives/2019/index.html
INFO  Generated: fonts/DressCodeIcons.woff
INFO  Generated: fonts/DressCodeIcons.svg
INFO  Generated: 2019/01/15/hello-world/index.html
INFO  Generated: style/swagger-ui-v3.css
INFO  Generated: style/doc.css
INFO  Generated: script/doc.js
INFO  Generated: style/swagger-ui-v2.css
INFO  13 files generated in 92 ms
~~~

**Comment by CMemorY180819** [comment]
I just forget to create md......

**Comment by KonstantinosMich91** [comment]
what do you mean my friend? create md where? i have the same issue and i cant use this theme

**Comment by rbarilani** [comment]
@KonstantinosMich91 I think you might need to create an md file like `source/index.md`

**Comment by KonstantinosMich91** [comment]
just did it.. nothing changed! 
https://github.com/zalando-incubator/hexo-theme-doc/issues/154 i just uploaded my issue here. if you can help me i'll be grateful

**Comment by rbarilani** [comment]
@KonstantinosMich91 something that can really help is having your project... is that possible? Can you have a repositories on github with your project?

**Comment by KonstantinosMich91** [comment]
https://github.com/KonstantinosMich91/hexo-theme-doc-issue

**Comment by rbarilani** [comment]
@KonstantinosMich91 Cool thanks that helps a lot!
