### ISSUE TITLE
 Chinese search Can be supported and like this

### ISSUE THREAD

**Issue by miaojf** [zalando-incubator/hexo-theme-doc#148]
![image](https://user-images.githubusercontent.com/10215067/51425864-e0577200-1c1c-11e9-86e6-886fe191ffbb.png)

**Comment by miaojf** [comment]
Thank you very much for your hexo theme 
 http://doc.agilebpm.cn/

**Comment by bhaskarmelkani** [comment]
@miaojf thanks for the valuable input 👍

**Comment by miaojf** [comment]
yes   ,  Would you consider using Algolia ?

**Comment by miaojf** [comment]
I agree.  thank you

**Comment by bhaskarmelkani** [comment]
I have created an issue for the same. It has just basics for now, I will update the ticket with further details in a while.
https://github.com/zalando-incubator/hexo-theme-doc/issues/150
