### ISSUE TITLE
Search returning posts but no links to post appear in result list

### ISSUE THREAD

**Issue by tomislavstrugacevacbusiness** [zalando-incubator/hexo-theme-doc#152]
## Expected Behavior

In search I type in term, results are shown but the link is missing
http://prntscr.com/mf0j97

**Comment by rbarilani** [comment]
Are those pages or posts? can you give me the link of the github repo?

**Comment by rbarilani** [comment]
@tomislavstrugacevacbusiness closing this issue since stale
