### ISSUE TITLE
How can I add an image in my post?

### ISSUE THREAD

**Issue by hecongy** [zalando-incubator/hexo-theme-doc#158]
According to the [doc](https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/writing.html), we should put all the posts in the source folder, then how can I use hexo asset folder feature? Or how can I add an image in my post?

**Comment by rbarilani** [comment]
@hecongy By using this theme, you will create pages not posts. Then you can normally embed images with markdown.
