### ISSUE TITLE
Can I use a global variable in my MD?

### ISSUE THREAD

**Issue by Junior2Ran** [zalando-incubator/hexo-theme-doc#171]
There are several pages using a code block like below:
```
<scirpt src="http://xxx.xxx.com/npm/MyLib@1.1.0" />
```
`MyLib` is updating fraquently, so I want to define an variable `var version = 1.1.0` somewhere, and the I can just use the custom variable in the markdown documents.

So is there a way I can do this thing? How should I do?

**Comment by Junior2Ran** [comment]
I have tried hexo variables, but it even didn't work?
I declared an variable in `config.yaml`
```
version: 1.1.0
```
and then in `.md` I used `{{theme.version}}` `{{theme_config.version}}` `{{config.version}}`, but none of them worked.

Then I tried hexo default variables `{{theme}}` and `{{config}}`, it also didn't work!
What happened? Is there anyone can help me...?

**Comment by rbarilani** [comment]
@Junior2Ran sincerly I never tried the feature that you describe  (using variables inside MD) my self... can you show me the documentation so I can maybe better understand the feature, and how is supposed to be implemented? do you maybe have some other hexo theme where you have seen that feature working?

**Comment by rbarilani** [comment]
Closing this issue since stale
