### ISSUE TITLE
Long logo text breaks layout

### ISSUE THREAD

**Issue by Nagogus** [zalando-incubator/hexo-theme-doc#26]
![screen shot 2017-10-25 at 17 40 37](https://user-images.githubusercontent.com/853907/32008188-e51dcd72-b9ab-11e7-8c5e-a1a7ed64b55a.png)

See attached

**Comment by rbarilani** [comment]
@Nagogus thx for your report. Will work on fix this soon.

**Comment by rbarilani** [comment]
@Nagogus I think that we need something like this: https://codepen.io/hal9087/pen/vWgdeZ

**Comment by Nagogus** [comment]
@rbarilani  with `line-height: 1.4em` it looks even better :)
