### ISSUE TITLE
Search missing from deployed site

### ISSUE THREAD

**Issue by internalfx** [zalando-incubator/hexo-theme-doc#35]
The search bar is missing from the site after being deployed.

it shows up fine with `hexo server`

I can see in the log that no such `lunr.json` is copied with `hexo deploy`

![image](https://user-images.githubusercontent.com/583701/32636086-78d1b0ae-c570-11e7-8eb5-bba6cd26572b.png)

![image](https://user-images.githubusercontent.com/583701/32636108-8ffe6056-c570-11e7-9a67-b3db658d97e8.png)

![image](https://user-images.githubusercontent.com/583701/32636126-a4681b0e-c570-11e7-9682-5ed668f2b2a2.png)

![image](https://user-images.githubusercontent.com/583701/32636177-e49ec5e2-c570-11e7-9fc4-2a0adfea7e71.png)

**Comment by rbarilani** [comment]
@internalfx PR #36 should fix the problem.
We will release a new version today. Thanks for using our tool. Stay tuned!

**Comment by internalfx** [comment]
I just updated and can confirm it is fixed, thank you.
