### ISSUE TITLE
fix(swagger): Check why swagger object returned by SwaggerParser.validate() breaks when converted to YAML.

### ISSUE THREAD

**Issue by bhaskarmelkani** [zalando-incubator/hexo-theme-doc#39]
The swagger object returned by [SwaggerParser.validate()](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#validateapi-options-callback), when converted to YAML contains some `&ref_`.

Check the behaviour.

**Comment by rbarilani** [comment]
closed via #37
