### ISSUE TITLE
Hosting HTML documentation?

### ISSUE THREAD

**Issue by erip** [zalando-incubator/hexo-theme-doc#62]
I'd like to first say that this seems like a fantastic tool for hosting documentation! Kudos on the good work.

It may be possible but seemingly undocumented, but is there a way to host or serve HTML generated by documentation engines like javadocs or sphinx? It would be a shame to need to convert them to Markdown and host them as separate pages.

**Comment by bhaskarmelkani** [comment]
Hey @erip ,

You don't have to convert the HTML files to markdown, hexo will parse and use them as it is.
* If you want to include the file to the project with the theme, you just have to remove `html`, `head` tags as the renderer will take the content of the `html` file and use it as it is and put it inside the body(to be specific `.doc-content` div ) of the page.

* But if you want the files to be used as it is, you can use `skip_render` option of [hexo_config](https://hexo.io/docs/configuration.html). The will be used as it is

**Comment by erip** [comment]
Ah, the latter seems super promising!

So if I'm running my hexo site locally on port 8080 and my `skip_render` directory contains

```
skip_render
├── coverage
│   └── index.html
│   └── ...
└── docs
│   └── index.html
│   └── ...
```

then my docs should be natively viewable from `http://localhost:8080/docs` and coverage from `http://localhost:8080/coverage`?

**Comment by bhaskarmelkani** [comment]
Hey,

I assume that your directory structure is following:-
```
source
|_____skip_render
|	├── coverage
|	│   	  └── index.html
|	│   	  └── ...
|	└── docs
|		   └── index.html
|		   └── ...
|_____someDoc.md
|_____otherDoc.md

```
If so, then they will be made available at `http://localhost:8080/skip_render/docs/index.html`.

I will say for naming, you can name the folder something more contextual than `skip_render`. 
For Eg.
```
source
|_____javadocs
|	├── coverage
|	│   	  └── index.html
|	│   	  └── ...
|	└── docs
|		   └── index.html
|		   └── ...
|_____someDoc.md
|_____otherDoc.md

```
and in your _config.yaml, you can write the following to make hexo skip these docs.
```yaml
#_config.yaml

skip_render: javadocs/**
```

**Comment by erip** [comment]
This is brilliant! Does `skip_render` also accept a list of directories? For example:

```
source
├── coverage
│   └── index.html
│   └── ...
└── javadocs
    └── index.html
    └── ...
```

```yaml
#_config.yaml

skip_render: javadocs/** coverage/**
```

**Comment by bhaskarmelkani** [comment]
Hey,

Yeah its an array of [glob expressions](https://github.com/isaacs/minimatch). So you can do following.

```yaml
skip_render:
    - javadocs/**
    - coverage/**
```

**Comment by erip** [comment]
Brilliant! This has been incredibly helpful. 😄 Thanks again for such a great theme.

**Comment by bhaskarmelkani** [comment]
Thanks @erip :)
