### ISSUE TITLE
Enum values not present in UI Model Definitions 

### ISSUE THREAD

**Issue by goodwillhacking** [zalando-incubator/hexo-theme-doc#94]
## Expected Behavior
  See Enum values in rendered page like: 
![selection_979](https://user-images.githubusercontent.com/3004543/34227118-0c7edfa4-e59a-11e7-950b-0b73adaeeadc.png)

Can be found at: http://petstore.swagger.io/

## Actual Behavior
Enum values not present in rendered page
![selection_978](https://user-images.githubusercontent.com/3004543/34227036-b755f86e-e599-11e7-9532-48968161df1f.png)

## Steps to Reproduce the Problem

  1. Use the default petstore 2.0 spec. For pet gender it contains enum male or female. 
  2. This does not show up in UI
  3.

## Specifications

  - NodeJS Version: v8.9.0
  - NPM Version: 5.5.1
  - OS:  DISTRIB_ID=LinuxMint   DISTRIB_RELEASE=17.1
  - Hexo Version: 3.4.3
  - Hexo-theme-doc: 0.1.1

 Hexo version output: 

- hexo: 3.4.3
- hexo-cli: 1.0.4
- os: Linux 3.13.0-37-generic linux x64
- http_parser: 2.7.0
- node: 8.9.0
- v8: 6.1.534.46
- uv: 1.15.0
- zlib: 1.2.11
- ares: 1.10.1-DEV
- modules: 57
- nghttp2: 1.25.0
- openssl: 1.0.2l
- icu: 59.1
- unicode: 9.0
- cldr: 31.0.1
- tz: 2017b

**Comment by rbarilani** [comment]
@goodwillhacking probably related to this [issue](https://github.com/swagger-api/swagger-ui/issues/3761).

Long story short, if you explicitly add a type to the enum declaration it works as expected.

**Comment by rbarilani** [comment]
closed via #99
