### ISSUE TITLE
feat(swagger): permanent download link

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/hexo-theme-doc#96]
## Expected Behavior

Download link for a swagger specification should not change if the content of the specification has changed.

## Actual Behavior

The link to download a swagger specification changes if the swagger specification has changed.
This prevent to share the link with others because there is a probability that it will change in the future.

## Steps to Reproduce the Problem

  1. Include swagger_ui 
  2. hexo genearte
  2. Check the download link
  3. change swagger specification content
  4. hexo generate
  5. check the download link, is changed 

## Specifications

  - NodeJS Version: v7.7.3
  - NPM Version: 5.6.0
  - OS: Mac OSX Yosemite
  - Hexo Version: 
hexo-cli: 1.0.3
os: Darwin 14.5.0 darwin x64
http_parser: 2.7.0
node: 7.7.3
v8: 5.5.372.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j

**Comment by rbarilani** [comment]
@bhaskarmelkani so after our discussion can we mark this as invalid?

**Comment by bhaskarmelkani** [comment]
@rbarilani Yes, the download path is  calculated from the file path of the spec file, so it will remain same as long as the path is same.
`downloadPath = hash(specPath)+specFileName`.

So, we can close this issue.
