### ISSUE TITLE
Swagger Required objects

### ISSUE THREAD

**Issue by goodwillhacking** [zalando-incubator/hexo-theme-doc#97]
Would like some clarification on required objects for valid swagger 2.0 spec. Based on swagger-object section version 2.0 spec which can be found here --> https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object

securityDefinitions and security (and others too)  are not required object for a specification file to be valid .

However when if I do not include the objects in my spec I get error messages similar to

" Data does not match any schemas from 'oneOf'........." `

Granted this may be version 3.0 (although I doubt there is a difference) When I test here: https://editor.swagger.io/ and remove the security definition object as well as all references to it it is recognized as valid.

**Comment by goodwillhacking** [comment]
Here is a spec without the security definitoons http://editor2.swagger.io/#!/

**Comment by bhaskarmelkani** [comment]
Hey,

We are using [`swagger-parser`](https://github.com/BigstickCarpet/swagger-parser) to validate swagger schema .
`securityDefinitions` and `sceurityRequirements` are not mandatory in Swagger 2.0.

I also checked removing `security` from the [petstore](https://github.com/zalando-incubator/hexo-theme-doc/blob/gh-pages-source/source/usage-and-configuration/swagger/petstore.yaml) schema     (in the `gh-pages-source` branch) and it works fine.

Can you please share the schema on which your testing it ?

> The link(swagger editor) you shared for schema shows schema stored in your local system, so cannot check whats wrong.

**Comment by rbarilani** [comment]
Stale, closing
